/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.stories.{js,jsx,ts,tsx,mdx}",
  ],

  theme: {
    fontFamily: {
      sans: ["Inter", "sans-serif"],
    },

    extend: {
      keyframes: {
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
      fontSize: {
        xs: ["0.75rem", "1.125rem"],
        small: ["0.875rem", "1.125rem"],
        md: ["1rem", "1.5rem"],
        lg: ["1.125rem", "1.75rem"],
        xl: ["1.25rem", "1.875rem"],
        "heading-1": [
          "4.5rem",
          {
            lineHeight: "5.625rem",
            letterSpacing: "-0.02rem",
          },
        ],
        "heading-2": [
          "3.75rem",
          {
            lineHeight: "4.5rem",
            letterSpacing: "-0.02rem",
          },
        ],
        "heading-3": [
          "3rem",
          {
            lineHeight: "3.75rem",
            letterSpacing: "-0.02rem",
          },
        ],
        "heading-4": [
          "2.25rem",
          {
            lineHeight: "2.75rem",
            letterSpacing: "-0.02rem",
          },
        ],
        "heading-5": [
          "1.875rem",
          {
            lineHeight: "2.375rem",
          },
        ],
        "heading-6": [
          "1.5rem",
          {
            lineHeight: "2rem",
          },
        ],
      },
      width: {
        xxs: "320px",
        xs: "384px",
        sm: "480px",
        md: "560px",
        lg: "640px",
        xl: "768px",
        "2xl": "1024px",
        "3xl": "1280px",
        "4xl": "1440px",
        "5xl": "1600px",
        "6xl": "1920px",
      },
      borderRadius: {
        xxs: "calc(var(--radius) - 6px)",
        xs: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 2px)",
        md: "var(--radius)",
        lg: "calc(var(--radius) + 2px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 12px)",
        "4xl": "calc(var(--radius) + 16px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // Text colors
        text: {
          primary: "hsl(var(--text-primary))",
          "primary-on-brand": "hsl(var(--text-primary_on-brand))",
          secondary: "hsl(var(--text-secondary))",
          "secondary-hover": "hsl(var(--text-secondary_hover))",
          "secondary-on-brand": "hsl(var(--text-secondary_on-brand))",
          tertiary: "hsl(var(--text-tertiary))",
          "tertiary-hover": "hsl(var(--text-tertiary_hover))",
          "tertiary-on-brand": "hsl(var(--text-tertiary_on-brand))",
          quaternary: "hsl(var(--text-quaternary))",
          "quaternary-on-brand": "hsl(var(--text-quaternary_on-brand))",
          white: "hsl(var(--text-white))",
          disabled: "hsl(var(--text-disabled))",
          placeholder: "hsl(var(--text-placeholder))",
          "placeholder-subtle": "hsl(var(--text-placeholder_subtle))",
          "brand-primary": "hsl(var(--text-brand-primary))",
          "brand-secondary": "hsl(var(--text-brand-secondary))",
          "brand-tertiary": "hsl(var(--text-brand-tertiary))",
          "error-primary": "hsl(var(--text-error-primary))",
          "error-secondary": "hsl(var(--text-error-secondary))",
          "warning-primary": "hsl(var(--text-warning-primary))",
          "warning-secondary": "hsl(var(--text-warning-secondary))",
          "success-primary": "hsl(var(--text-success-primary))",
          "success-secondary": "hsl(var(--text-success-secondary))",
        },
        // Border colors
        border: {
          primary: "hsl(var(--border-primary))",
          secondary: "hsl(var(--border-secondary))",
          tertiary: "hsl(var(--border-tertiary))",
          disabled: "hsl(var(--border-disabled))",
          "disabled-subtle": "hsl(var(--border-disabled_subtle))",
          brand: "hsl(var(--border-brand))",
          "brand-alt": "hsl(var(--border-brand_alt))",
          error: "hsl(var(--border-error))",
          "error-subtle": "hsl(var(--border-error_subtle))",
          warning: "hsl(var(--border-warning))",
          "warning-subtle": "hsl(var(--border-warning_subtle))",
          success: "hsl(var(--border-success))",
          "success-subtle": "hsl(var(--border-success_subtle))",
        },
        // Background colors
        bg: {
          primary: "hsl(var(--bg-primary))",
          "primary-alt": "hsl(var(--bg-primary_alt))",
          "primary-hover": "hsl(var(--bg-primary_hover))",
          "primary-solid": "hsl(var(--bg-primary-solid))",
          secondary: "hsl(var(--bg-secondary))",
          "secondary-alt": "hsl(var(--bg-secondary_alt))",
          "secondary-hover": "hsl(var(--bg-secondary_hover))",
          "secondary-subtle": "hsl(var(--bg-secondary_subtle))",
          "secondary-solid": "hsl(var(--bg-secondary-solid))",
          tertiary: "hsl(var(--bg-tertiary))",
          quaternary: "hsl(var(--bg-quaternary))",
          active: "hsl(var(--bg-active))",
          disabled: "hsl(var(--bg-disabled))",
          "disabled-subtle": "hsl(var(--bg-disabled_subtle))",
          overlay: "hsl(var(--bg-overlay))",
          "brand-primary": "hsl(var(--bg-brand-primary))",
          "brand-primary-alt": "hsl(var(--bg-brand-primary_alt))",
          "brand-secondary": "hsl(var(--bg-brand-secondary))",
          "brand-solid": "hsl(var(--bg-brand-solid))",
          "brand-solid-hover": "hsl(var(--bg-brand-solid_hover))",
          "brand-section": "hsl(var(--bg-brand-section))",
          "brand-section-subtle": "hsl(var(--bg-brand-section_subtle))",
          "error-primary": "hsl(var(--bg-error-primary))",
          "error-secondary": "hsl(var(--bg-error-secondary))",
          "error-solid": "hsl(var(--bg-error-solid))",
          "warning-primary": "hsl(var(--bg-warning-primary))",
          "warning-secondary": "hsl(var(--bg-warning-secondary))",
          "warning-solid": "hsl(var(--bg-warning-solid))",
          "success-primary": "hsl(var(--bg-success-primary))",
          "success-secondary": "hsl(var(--bg-success-secondary))",
          "success-solid": "hsl(var(--bg-success-solid))",
        },
        // Foreground colors
        fg: {
          primary: "hsl(var(--fg-primary))",
          secondary: "hsl(var(--fg-secondary))",
          "secondary-hover": "hsl(var(--fg-secondary_hover))",
          tertiary: "hsl(var(--fg-tertiary))",
          "tertiary-hover": "hsl(var(--fg-tertiary_hover))",
          quaternary: "hsl(var(--fg-quaternary))",
          "quaternary-hover": "hsl(var(--fg-quaternary_hover))",
          quinary: "hsl(var(--fg-quinary))",
          "quinary-hover": "hsl(var(--fg-quinary_hover))",
          senary: "hsl(var(--fg-senary))",
          white: "hsl(var(--fg-white))",
          disabled: "hsl(var(--fg-disabled))",
          "disabled-subtle": "hsl(var(--fg-disabled_subtle))",
          "brand-primary": "hsl(var(--fg-brand-primary))",
          "brand-primary-alt": "hsl(var(--fg-brand-primary_alt))",
          "brand-secondary": "hsl(var(--fg-brand-secondary))",
          "error-primary": "hsl(var(--fg-error-primary))",
          "error-secondary": "hsl(var(--fg-error-secondary))",
          "warning-primary": "hsl(var(--fg-warning-primary))",
          "warning-secondary": "hsl(var(--fg-warning-secondary))",
          "success-primary": "hsl(var(--fg-success-primary))",
          "success-secondary": "hsl(var(--fg-success-secondary))",
        },

        primary: {
          50: "hsl(var(--utility-primary-50))",
          "50-alt": "hsl(var(--utility-primary-50_alt))",
          100: "hsl(var(--utility-primary-100))",
          "100-alt": "hsl(var(--utility-primary-100_alt))",
          200: "hsl(var(--utility-primary-200))",
          "200-alt": "hsl(var(--utility-primary-200_alt))",
          300: "hsl(var(--utility-primary-300))",
          "300-alt": "hsl(var(--utility-primary-300_alt))",
          400: "hsl(var(--utility-primary-400))",
          "400-alt": "hsl(var(--utility-primary-400_alt))",
          500: "hsl(var(--utility-primary-500))",
          "500-alt": "hsl(var(--utility-primary-500_alt))",
          600: "hsl(var(--utility-primary-600))",
          "600-alt": "hsl(var(--utility-primary-600_alt))",
          700: "hsl(var(--utility-primary-700))",
          "700-alt": "hsl(var(--utility-primary-700_alt))",
          800: "hsl(var(--utility-primary-800))",
          "800-alt": "hsl(var(--utility-primary-800_alt))",
          900: "hsl(var(--utility-primary-900))",
          "900-alt": "hsl(var(--utility-primary-900_alt))",
          DEFAULT: "hsl(var(--utility-primary-500))",
        },
        gray: {
          50: "hsl(var(--utility-gray-50))",
          100: "hsl(var(--utility-gray-100))",
          200: "hsl(var(--utility-gray-200))",
          300: "hsl(var(--utility-gray-300))",
          400: "hsl(var(--utility-gray-400))",
          500: "hsl(var(--utility-gray-500))",
          600: "hsl(var(--utility-gray-600))",
          700: "hsl(var(--utility-gray-700))",
          800: "hsl(var(--utility-gray-800))",
          900: "hsl(var(--utility-gray-900))",
          DEFAULT: "hsl(var(--utility-gray-500))",
        },
        error: {
          50: "hsl(var(--utility-error-50))",
          100: "hsl(var(--utility-error-100))",
          200: "hsl(var(--utility-error-200))",
          300: "hsl(var(--utility-error-300))",
          400: "hsl(var(--utility-error-400))",
          500: "hsl(var(--utility-error-500))",
          600: "hsl(var(--utility-error-600))",
          700: "hsl(var(--utility-error-700))",
          800: "hsl(var(--utility-error-800))",
          900: "hsl(var(--utility-error-900))",
          DEFAULT: "hsl(var(--utility-error-500))",
        },
        warning: {
          50: "hsl(var(--utility-warning-50))",
          100: "hsl(var(--utility-warning-100))",
          200: "hsl(var(--utility-warning-200))",
          300: "hsl(var(--utility-warning-300))",
          400: "hsl(var(--utility-warning-400))",
          500: "hsl(var(--utility-warning-500))",
          600: "hsl(var(--utility-warning-600))",
          700: "hsl(var(--utility-warning-700))",
          800: "hsl(var(--utility-warning-800))",
          900: "hsl(var(--utility-warning-900))",
          DEFAULT: "hsl(var(--utility-warning-500))",
        },
        success: {
          50: "hsl(var(--utility-success-50))",
          100: "hsl(var(--utility-success-100))",
          200: "hsl(var(--utility-success-200))",
          300: "hsl(var(--utility-success-300))",
          400: "hsl(var(--utility-success-400))",
          500: "hsl(var(--utility-success-500))",
          600: "hsl(var(--utility-success-600))",
          700: "hsl(var(--utility-success-700))",
          800: "hsl(var(--utility-success-800))",
          900: "hsl(var(--utility-success-900))",
          DEFAULT: "hsl(var(--utility-success-500))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
