export enum ServiceType {
  AI_VIDEO_GENERATION = "AI_VIDEO_GENERATION",
  PROFESSIONAL_EDITOR = "PROFESSIONAL_EDITOR",
  TALKING_BABY_PODCAST = "TALKING_BABY_PODCAST",
  AVATAR_GENERATOR = "AVATAR_GENERATOR",
  POV_VIDEOS = "POV_VIDEOS",
}
